version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      DB_NAME: ledn
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  api:
    container_name: ledn-api
    image: latest/ledn-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
volumes:
  mongodb_data_container:
